version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Build stage"

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: echo "Deploying to AWS"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
