version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m unittest discover
      - run:
          name: Deploy to AWS
          command: |
            ssh -i /c/Users/Ana/Desktop/CA_DEV/devops-ec-access.pem ec2-user@SEU_IP_PUBLICO "cd SimpleApplication && git pull && python app.py"
      - run:
            name: Install dependencies
            command: pip install -r ./requirements.txt          
      

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

      